[package]
name = "tiny-ml"
version = "0.1.0"
edition = "2021"
authors = ["milim <https://github.com/MilimTheTrueOne>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
